title: Params Default
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        options:
          type: tab
          title: PLUGIN_ADMIN.OPTIONS

          fields:
            taxonomies:
              type: section
              title: PLUGIN_ADMIN.TAXONOMIES
              underline: true

              fields:
                header.taxonomy:
                  validate:
                    required: true
        advanced:
          type: tab
          title: Avançado

          fields:
            columns:
              type: columns
              fields:
                column1:
                  type: column
                  fields:

                    name:
                      replace@: true
                      type: select
                      classes: fancy
                      label: PLUGIN_ADMIN.PAGE_FILE
                      help: PLUGIN_ADMIN.PAGE_FILE_HELP
                      default: default
                      options:
                        default: Padrão
                        lista_de_topicos: Lista de Tópicos
                        blog_list: Blog
                        blog_item: Blog Item
                        form: Formulário
                        formdata: Resposta de Formulário


        param:
          type: tab
          title: Parâmetros

          fields:
            header_acl:
              type: section
              title: ACL
              underline: true
              import@:
                type: partials/acl
                context: blueprints://
            header_menu:
              type: section
              title: Âncoras
              underline: true
            header.anchors.active:
              type: toggle
              label: Ativar Âncora
              highlight: 1
              default: 0
              help: Permita o plugin de âncora na página
              options:
                1: Sim
                0: Não
              validate:
                type: bool
            header.menuright:
              type: toggle
              label: Habilitar Menu
              highlight: 1
              default: 1
              help: Escolha se quer que apareça um menu na lateral direita da página baseado na opção de título abaixo
              options:
                1: Sim
                0: Não
              validate:
                type: bool
            header.tagtitle:
              type: select
              size: small
              classes: fancy
              default: h2
              label: Selecione o filtro
              help: Selecione qual o tipo de título será usado para filtrar na página e gerar o menu lateral esquerdo
              options:
                h1: Título 1 (h1)
                h2: Título 2 (h2)
                h3: Título 3 (h3)
                h4: Título 4 (h4)
            header.terms:
              type: text
              label: Retirar títulos
              help: Coloque os termos separados por vírgula que deseja retirar do filtro. Ex: Caso não queira que apareça o link de um determinado título na lista de âncoras da lateral, copie e cole o texto do título aqui.
