title: Params Default
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        param:
          type: tab
          title: Parâmetros

          fields:
            header_acl:
              type: section
              title: ACL
              underline: true
            header.access:
              type: array
              label: Regra de Acesso
              placeholder_key: Regra
              placeholder_value: Valor(0 ou 1)